### ISSUE TITLE
library for using i2c and spi pins on pynq z1 

### ISSUE THREAD

**Issue by velloregorilla** [Xilinx/PYNQ#1010]
I want my pynq to communicate with a Arduino, but I am not able to find any API or library that can do that.  I can only use the gpio pins for this purpose.

**Comment by giunatale** [comment]
Hi @velloregorilla, I would kindly suggest for next time to please follow the issue template when posting issues.

As this is a support question, I am asking you to redirect this to our support forum https://discuss.pynq.io.

Closing
