### ISSUE TITLE
ModuleNotFoundError: No module named 'pynq.utils'

### ISSUE THREAD

**Issue by HotCoCoC** [Xilinx/PYNQ#1021]
* PYNQ version (e.g. v2.5):
* Board name (e.g. Pynq-Z2):
* Pull request type (bug fix):
* Description:
I ran into this problem when I installed the "Helloworld" project
ModuleNotFoundError: No module named 'pynq.utils'
How do I solve it?

**Comment by cr4zy0w1** [comment]
Having the same problem here.
I was wondering why is this issue closed?
