### ISSUE TITLE
AttributeError: 'PynqBuffer' object has no attribute 'free_buffer'

### ISSUE THREAD

**Issue by cxubrix** [Xilinx/PYNQ#1046]
https://github.com/Xilinx/PYNQ/blob/3f634506e4d428cb07bb5a57c1d95cab0c803d20/pynq/buffer.py#L127

I believe it should call `freebuffer()` not `free_buffer()` this causes  
`AttributeError: 'PynqBuffer' object has no attribute 'free_buffer'` when using buffer in with statement

**Comment by VicerExciser** [comment]
^ bump.
Why dis no fixed yet?
Easy as `sed -i 's/free_buffer/freebuffer/g' pynq/buffer.py`

**Comment by giunatale** [comment]
It should be fixed now, check the file out on the master branch.
