### ISSUE TITLE
adding custom library 

### ISSUE THREAD

**Issue by savan1213** [Xilinx/PYNQ#1053]
**For general questions, please use [the PYNQ discussion forum](https://discuss.
pynq.io/). We actively monitor the forum and try to answer every question 
there.**

Before submitting a pull request, you can also raise an issue that explains the 
problem the pull request is trying to resolve. Feel free to close the issue once
 the pull request has been merged.

If you still want to raise an issue here, please give us as much detail as 
possible to the issue you are seeing - we've listed some helpful fields below.

* PYNQ version -v2.4:
* Board name microzed 7010::
* Description:
can i  add my custom library code in the rootfs and build it again.so that libraries's so files will be loaded at the booting time?

**Comment by giunatale** [comment]
Hi @savan1213, as this is a technical question more than a bug, I would advise you to use our forum and post your question there: https://discuss.pynq.io

The issue tracker is meant to report bugs in the code base, so I will have to close this one. Hope to see you on https://discuss.pynq.io
