### ISSUE TITLE
File content missing in the path /master/boards/Pynq-Z2/base/notebooks/video

### ISSUE THREAD

**Issue by qqq89513** [Xilinx/PYNQ#1072]
The .ipynb files [here](https://github.com/Xilinx/PYNQ/tree/master/boards/Pynq-Z2/base/notebooks/video) in this repo are lack of content.
Open any one of the files, you see only **path** for HDMI examples for PYNQ Z1.

**Comment by giunatale** [comment]
They are symlinks, this is intentional as they are identical to the Z1 notebooks and this avoids to have copies of the same file in multiple places. A symlink will just point to the original, single copy, therefore updating that one will propagate the update to all the other symlinks.

Closing
