### ISSUE TITLE
zybo-z7(PYNQ)

### ISSUE THREAD

**Issue by XiaoHangGe** [Xilinx/PYNQ#1119]
I'm trying to create a Pynq 2.3 image for my Zybo Z7 board.
I've actually completed all the steps:
- Created the Petalinux BSP (Petalinux 2018.2)

- Ran the "image_from_prebuilt" script, with the board-agnostic image 2.3

The build process was completed, I have a ZyboZ720 Pynq 2.3 image, but my board just doesn't boot it (Jumper settings are correct though).

* PYNQ version :v2.3
* Board name :ZYBO-Z7
ERROR:
![INFO](https://user-images.githubusercontent.com/29398677/92147502-d1ebb780-ee4d-11ea-9292-438861beb067.PNG)

**Comment by giunatale** [comment]
Hi @XiaoHangGe, please re-direct this question to our support forum discuss.pynq.io
We use the issue tracker for reporting bugs in the code base. 
I will have to close this issue. Thank you for your patience
