### ISSUE TITLE
SD build for PYNQ-Z1 failed v2.6.2,  

### ISSUE THREAD

**Issue by jmeyerson999** [Xilinx/PYNQ#1207]
I'm using a VM with Ubuntu v18.04.4, and Vitis & Petalinux 2020.1 to build the SD Image for PYNQ-Z1. I'm getting an error about an expat download not being found when crosstool-ng is running. I've also run into this issue when I tried to build on image_v2.6.0, image_2.7, and master.

Does anyone know how to get around this? 

[build v2.6.2 error log.txt](https://github.com/Xilinx/PYNQ/files/6617224/build.v2.6.2.error.log.txt)

**Comment by mariodruiz** [comment]
Hi @jmeyerson999,

Can you please post your question into the PYNQ forums? https://discuss.pynq.io/c/support/30
