### ISSUE TITLE
A bug in sdbuild/Makefile

### ISSUE THREAD

**Issue by qixingzhang** [Xilinx/PYNQ#1312]
In [sdbuild/Makefile line 146](https://github.com/Xilinx/PYNQ/blob/master/sdbuild/Makefile#L146), adding meta-pynq layer to USER_LAYER_0 will overwrite any pre-added user layers.

**Comment by schelleg** [comment]
Not an issue in latest builds. If this is still an issue re-open it as a [[discuss.pynq.io](http://discuss.pynq.io/)](https://discuss.pynq.io/) post.
