### ISSUE TITLE
Add documentation regarding AXI Interrupt controller and their edge vs level detection setting

### ISSUE THREAD

**Issue by datMaffin** [Xilinx/PYNQ#1315]
Please add documentation regarding AXI Interrupt controller and their edge vs level detection setting. Specifically that the Vivado block design automation seems to default to "level detection". And in my (limited) experience did therefore not work as expected until I manually switched it back to "edge detection".

Granted, I am not that experienced with vivado and hardware design in general, but it took me a pretty long time to figure out this issue with interrupts.

If this is already mentioned in the documentation somewhere and I just did not notice it, please make it more prevalent.

For more details see also: https://discuss.pynq.io/t/zynq-ps7-interrupts/198/10
(There was not yet any response. However, because I believe that this is an issue and not a discussion, I decided to additionally open this issue.)

References to relevant documentation, i.e., where it might make sense to mention this detail:
* https://github.com/Xilinx/PYNQ/blob/image_v2.7/docs/source/overlay_design_methodology/pynq_and_asyncio.rst
* https://github.com/Xilinx/PYNQ/blob/image_v2.7/docs/source/pynq_libraries/interrupt.rst 
  - If someone will follow this tutorial, that person will very likely end up with an AXI Interrupt Controller where interrupt detection is set to "level detection" and therefore observe weird behavior.

---

The Vivado software I used was 2020.1.

**Comment by jancumps** [comment]
this may be resolved by #1318
