### ISSUE TITLE
update_pynq.sh failed

### ISSUE THREAD

**Issue by yunqu** [Xilinx/PYNQ#132]
![image](https://cloud.githubusercontent.com/assets/14114006/17827103/b9c847e8-662c-11e6-8d1d-64c4797c240a.png)

**Comment by promach** [comment]
For the latest pynq v2 SD card image , update_pynq.sh is deprecated. So, how should I deal with [https://github.com/VectorBlox/PYNQ#vectorblox-pynq-fork](https://github.com/VectorBlox/PYNQ#vectorblox-pynq-fork) ?
