### ISSUE TITLE
Pynq 2.7 for ZCU208 

### ISSUE THREAD

**Issue by sirjansel0t** [Xilinx/PYNQ#1322]
According to the release notes for pynq 2.7 it supports rf data converters and clocks for the gen3.  Does pynq 2.7 support the zcu208 or any other gen 3 eval board?  Will you guys release an image?

**Comment by jramsey123** [comment]
Has there been any progress made on getting PYNQ running on the ZCU208?

**Comment by jramsey123** [comment]
Has there been any progress made on getting PYNQ running on the ZCU208?

**Comment by plysaght** [comment]
PYNQ support for the ZCU208 is not currently plan of record but it is being reviewed. If would be helpful to gather any use cases that would you can offer to make the case for doing th port. 
FYI there is a 3rd-party port of PYNQ for the ZCU216 here: https://github.com/sarafs1926/ZCU216-PYNQ

**Comment by mariodruiz** [comment]
Starting from PYNQ v3.0, the ZCU208 is supported in the RFSoC-PYNQ repository. https://github.com/Xilinx/RFSoC-PYNQ/tree/master/boards/ZCU208
