### ISSUE TITLE
PYNQ Z2 Board File Missing

### ISSUE THREAD

**Issue by CPA872** [Xilinx/PYNQ#1340]
**For general questions, please use [the PYNQ discussion forum](
https://discuss.pynq.io/). We actively monitor the forum and try to answer 
every question there.**

Before submitting a pull request, you can also raise an issue that explains the 
problem the pull request is trying to resolve. Feel free to close the issue once
 the pull request has been merged.

If you still want to raise an issue here, please give us as much detail as 
possible to the issue you are seeing - we've listed some helpful fields below.

* PYNQ version (e.g. v2.6):
* Board name (e.g. Pynq-Z2):
* Pull request type (bug fix / new feature):
* Pull request number:
* Description:

The PYNQ Z2 Board File is missing. The download link does not work anymore. Please Fix! Thanks!

**Comment by mariodruiz** [comment]
Hi,

Where is the board file missing? 

Mario
