### ISSUE TITLE
XRT Device fails with newer XRT versions

### ISSUE THREAD

**Issue by quetric** [Xilinx/PYNQ#1344]
* PYNQ version: 2.7.0 (pip installed)
* Board name: Alveo (any)

* Description: XRT version identification fails with newer XRT versions. This is because xrt_device.py at line 88 tries to do `xbutil dump` to get the version, but that command no longer exists. 

* Suggested fix: The function should run `xbutil --version` instead (or as a backup if `xbutil dump` fails), and parse the first line of output e.g. `output.stdout.splitlines()[0].split(": ")[1].split(".")`

**Comment by mariodruiz** [comment]
Hi @quetric, we are working on a solution. 
There is a PR already opened for this here https://github.com/Xilinx/PYNQ/pull/1343 

Another workaround for now is to use the `--legacy` switch https://discuss.pynq.io/t/pynq-on-alveo-and-xrt-2021-2/3568/2?u=marioruiz

**Comment by quetric** [comment]
Thank you @mariodruiz, work-around noted.

**Comment by mariodruiz** [comment]
Fixed in v3.0
