### ISSUE TITLE
.spec file ARCH_ line requires a CR or build for 3rd party boards fail

### ISSUE THREAD

**Issue by FredKellerman** [Xilinx/PYNQ#1346]
Basically it turns out if you use a trying to be to smart for its own good editor: it thinks a .spec file is a MS-DOS type file and inserts CRs.  But if you create the PYNQ .spec file using a different method and do not put a CR character at the end of the ARCH_ line, the Makefile errors out very early with:

```makefile
make: *** No rule to make target '/foo-PYNQ/PYNQ-git/sdbuild/boot/image_arm', needed by '/foo-PYNQ/PYNQ-git/sdbuild/build/foo/image.its'.  Stop.
Status: Build FAILED
```
Git diff finally made it clear what was going on.  The first revision without CR did not work, the 2nd shown in the diff with the CR does.
```
diff --git a/foo/foo.spec b/foo/foo.spec
index e34887e..4a53775 100755
--- a/foo/foo.spec
+++ b/foo/foo.spec
@@ -1,4 +1,4 @@
-ARCH_foo := arm 
+ARCH_foo := arm^M
 BSP_foo := foo.bsp
```

The Makefile needs a little tweak if possible to make this behave with or without CR.

**Comment by skalade** [comment]
Thanks Fred!
