### ISSUE TITLE
AttributeError: Could not find IP or hierarchy memory in overlay

### ISSUE THREAD

**Issue by nagendra7890** [Xilinx/PYNQ#1360]
I have used allocate instead of xlnk. is there any different way to load the weights in memory or is it possible to load weights in HLS? did anyone solve this issue?

![image](https://user-images.githubusercontent.com/51146044/163107975-25342564-d47e-4dd7-a52f-e020fcc40a4a.png)

![image](https://user-images.githubusercontent.com/51146044/163107995-75471075-db1e-4352-94e9-e2973601b144.png)

![image](https://user-images.githubusercontent.com/51146044/163108016-21b17aa2-5907-495c-9ed0-509b874ee112.png)

**Comment by mariodruiz** [comment]
You already have a post open on discuss.pynq.io https://discuss.pynq.io/t/dpu-pynq-on-zcu104-and-zcu111/3853
