### ISSUE TITLE
Domain for the Vivado board files has changed

### ISSUE THREAD

**Issue by hobnob11** [Xilinx/PYNQ#1361]
I'd submit a merge request but i'm not sure if this is the only place this is linked, however: 

The download link for the Z2 board file found here: 
`https://pynq.readthedocs.io/en/latest/overlay_design_methodology/board_settings.html#vivado-board-files`
Links here: `https://www.tul.com.tw/productspynq-z2.html` which as of 30/04/2022 is 404.
I found what appears to be the new domain for the same page here: `https://www.tulembedded.com/FPGA/ProductsPYNQ-Z2.html`

**Comment by mariodruiz** [comment]
This will be fixed when #1342 is merged

**Comment by mariodruiz** [comment]
Merged in v3.0
