### ISSUE TITLE
What version of petalinux we should use for PYNQ 2.7?

### ISSUE THREAD

**Issue by Kgfu** [Xilinx/PYNQ#1365]
PYNQ version = 2.7
Board name = PYNQ-Z2
Description:
We are trying the PYNQ SD Card image generation, but the guide doesn't point out the version of petalinux we should use for the PYNQ 2.7.
I'm installing the VM with Ubuntu 18.04 and Xilinux tool 2020.2.
Does anyone know the peta-linux part?

**Comment by mariodruiz** [comment]
Vivado and petalinux go hand in hand, so you need the same version of petalinux as described in the documentation https://pynq.readthedocs.io/en/latest/pynq_sd_card.html?highlight=petalinux#use-vagrant-to-prepare-ubuntu-os
