### ISSUE TITLE
Incorrect ip_dict when using multibank Alveo memories

### ISSUE THREAD

**Issue by quetric** [Xilinx/PYNQ#1370]
* PYNQ version (e.g. v2.6): 2.7.1
* Board name (e.g. Pynq-Z2): Alveo U280
* Description:

ip_dict is incorrect when multiple memory banks are attached to one kernel AXIMM interface, e.g. for HBM[0:5] the ip_dict will indicate HBM[5]

**Comment by mariodruiz** [comment]
Hi @quetric,

What would you expect the dict to report?

**Comment by quetric** [comment]
Hi @mariodruiz 

The "memory" entry for the AXIMM interface/register should say HBM[0:5] indicating that all banks from 0 to 5 are connected to that interface. I think this is preferable since it corresponds to the vitis configuration setting that was used to make the connection. Alternatively the dictionary entry could have a list of banks e.g. "memory": ["HBM[0]", "HBM[5]" etc]
