### ISSUE TITLE
Default vagrant version is 18.04 not 20.04 

### ISSUE THREAD

**Issue by ghuangatlbl** [Xilinx/PYNQ#1380]
I am trying to build the sd image and follow the instruction started with vagrant. 
The instruction https://pynq.readthedocs.io/en/v2.7.0/pynq_sd_card.html says 

![image](https://user-images.githubusercontent.com/18746409/186249178-b5d2c2b2-7aed-421b-bfaf-c15338eb0055.png)

But what I got is 18.04. 
And check the source in the Vagrantfile also says disk image is 18.04
![image](https://user-images.githubusercontent.com/18746409/186249353-33391450-1ed0-47a9-b7f2-232bedaad0c7.png)

Should I use the 18.04 or 20.04? Or even better, will 22.04 work?

**Comment by schelleg** [comment]
We will move to docker flows in the future. If this is still an issue re-open it as a [[discuss.pynq.io](http://discuss.pynq.io/)](https://discuss.pynq.io/) post.
