### ISSUE TITLE
How to download PYNQ rootfs aarch64 v2.6?

### ISSUE THREAD

**Issue by CharlesChen1024** [Xilinx/PYNQ#1404]
Hi,
I want to install PYNQ on ZCU102. I prebuilt a PYNQ image file, but I don't know where to download PYNQ rootfs aarch64 v2.6. My petalinux and vivado's version is 2020.1 and os is ubuntu18.04.4.

**Comment by cathalmccabe** [comment]
https://bit.ly/pynq_rootfs_aarch64_v2_6

**Comment by CharlesChen1024** [comment]
@cathalmccabe Thanks.
