### ISSUE TITLE
PYNQ file system to add DPU, DPU part is not displayed?

### ISSUE THREAD

**Issue by Noah-naihe** [Xilinx/PYNQ#1417]
Here I'm using the zcu102 board. 
I imported the vivado project containing DPU into the petalinux project, and generated the corresponding image through the petalinux tool, and successfully ran the demo. However, after packaging the project successfully bsp, I successfully transplanted the PYNQ file system according to the way of modifying the homemade board. However, I cannot find the file system Settings of DPU, such as the library of vitis ai added to the file system. I would like to know whether the file system Settings of the original project are retained during the PYNQ transplantation process, or whether the dpu parts of the original project are also changed?

**Comment by schelleg** [comment]
PYNQ doesn't support using the DPU integrated in Vivado.  If this is still an issue re-open it as a [[discuss.pynq.io](http://discuss.pynq.io/)](https://discuss.pynq.io/) post.
