### ISSUE TITLE
Change Password of Jupyter Notebook

### ISSUE THREAD

**Issue by RafaelVieira99** [Xilinx/PYNQ#1420]
I recently downloaded the most recent pynq image, **3.0**, and I want to change the password of my jupyter notebook.
Changing it in the terminal as if it was a linux system does not affect the jupyter notebook password.
The only solution that I found online was in the **PYNQ FAQ**  [https://pynq.readthedocs.io/en/latest/faqs.html#how-do-i-change-the-jupyter-notebook-password](url)

I want to report that this solution is **outdated**, and only works for older versions of IPython that are not compatible with the rest of libraries in the newer version of PYNQ. Either adapt a whole bunch of libraries just to change the password, or just use older versions of PYNQ if you want to have more security.

Maybe there is a way to have the encrypted code for the password other than using IPython, and if that is the case, please provide a solution

Thanks

**Comment by timkpaine** [comment]
This is configurable just via vanilla jupyter mechanisms, no? https://jupyter-notebook.readthedocs.io/en/stable/public_server.html

**Comment by RafaelVieira99** [comment]
Thats right! thanks.
The problem was that I was trying the way that it was shown on FAQ, but following those jupyter documents it works fine!

**Comment by mariodruiz** [comment]
Hi @RafaelVieira99,

Would you like to do a PR updating the documentation?

**Comment by RafaelVieira99** [comment]
Sure, I have never done it but I will try to do it later today
