### ISSUE TITLE
Can PYNQ interact with the interface of hls:: stream？

### ISSUE THREAD

**Issue by zyt1024** [Xilinx/PYNQ#1426]
Hello, I'm using the` Alveo accelerator boards U200`. I package the kernel as xclbin,use the interface `hls:: stream`. Can PYNQ interact with this interface?
sush as:
``` c++
void myproject(
    hls::stream<input_t> &input_3,
    hls::stream<result_t> &layer23_out
)
```

**Comment by mariodruiz** [comment]
Hi @zyt1024,

No, PYNQ does not interact directly with `hls::stream`.  
PYNQ only interacts directly with AXI4-Lite, but it can allocate memory in the Alveo global memory that the accelerator can access via AXI4 (memory-mapped).

Please, for support questions use the PYNQ forum https://discuss.pynq.io/

Mario
