### ISSUE TITLE
SPI-Core crashes python kernel / linux kernel when access register_map

### ISSUE THREAD

**Issue by TRnhld** [Xilinx/PYNQ#1435]
* PYNQ version: 3.0.1
* Board name: MicroZed 7020 (AES-Z7MB-7Z020)
* Pull request type: bug fix
* __Description__:
  * I've got a desigh with AXI Quad SPI (V3.2) Core. with following Configuration
    * Performance Mode = Disabled
    * Mode = Quad
    * No. of Slaves = 1
    * Slave Device = Spansion
    * FIFO Depth = 16 (also tried 256)
    * STARTUP Primitive = disabled
  * after loading the Overlay and accessing the IP's register_map, the python kernel crashes
```python
o = Overlay(r'overlay/design7.xsa')
o.qspi_master_hier.axi_quad_spi.register_map
```
![Screenshot 2023-11-21 095214](https://github.com/Xilinx/PYNQ/assets/112692081/7a23ab48-4589-47ad-b9d4-65087ed3ce0b)

* Locating error-source
  * tracking the error in  the pynq libraris i noticed, the registers ger acessed when calling *.register_map
  * __the *AXI Quad SPI*-IP seems to have the has a special behaviour when accessing an empty RX-FIFO `SPI DRR` - causing timeout on AXI when FIFO is empty__
  * the call for accessing this address happens in `__init__`-function of class `pynq.registers.RegisterMap`

based on this I created some sample code to see where the python kernel crashes:

```python
from pynq import Overlay
o = Overlay(r'overlay/design7.xsa')
rs = pynq.registers.RegisterMap.create_subclass(o.qspi_master_hier.axi_quad_spi._register_name, o.qspi_master_hier.axi_quad_spi._registers)(o.qspi_master_hier.axi_quad_spi.mmio.array)
buf = o.qspi_master_hier.axi_quad_spi.mmio.array

array32 = buf.view(dtype='u4')

array32[0x10] = 0xa # resetting spi core

for k, v in rs._register_classes.items():
    index = v[1] // 4
    print("%02X "  % (v[1]//4), end='')

sleep(1)
print("\n")

for k, v in rs._register_classes.items():
    index = v[1] // 4
    if index == 0x1B:
        continue
    print("%02X "  % (v[1]//4), end='')
    sleep(0.1)
    array = array32[index:index+1]
    print("= %02X" % array[0])
    
sleep(1)
print("\n")

for k, v in rs._register_classes.items():
    index = v[1] // 4
    print("%02X "  % (v[1]//4), end='')
    sleep(0.1)
    array = array32[index:index+1] # axi bus gets timeout when trying to excess empty rx fifo
    print("= %02X" % array[0])
```
Output:
```
18 19 10 18 19 1C 1D 1E 07 1A 1B 08 0A 

18 = 180
19 = AD
10 = 00
18 = 180
19 = AD
1C = 01
1D = 00
1E = 00
07 = 00
1A = 00
08 = 400
0A = 00


18 = 180
19 = AD
10 = 00
18 = 180
19 = AD
1C = 01
1D = 00
1E = 00
07 # *Python kernel Restarts here*
```

* Additional tries and findings
  * I also did an implementation with same settings of _AXI Quad SPI_ accept putting the core into performance mode
    * Note: having to do some other "going around bugs" - See [here](https://github.com/Xilinx/PYNQ-Metadata/issues/14)
    * here, the core gets accessed by mmap - library
    * in class `pynq.pl_server.embedded_device.EmbeddedDevice` the function `mmap()` will be called.
      * the line 599 `array = np.frombuffer(mem, np.uint32, length >> 2, virt_offset)` will cause the whole linux kernel to crash.

**Comment by schelleg** [comment]
This is a special case when accessing the entire register map - PYNQ doesn't support this register behavior.  

If this is still an issue re-open it as a [discuss.pynq.io](http://discuss.pynq.io/) post.
