### ISSUE TITLE
Broken link for supported multiple boards

### ISSUE THREAD

**Issue by jasvinderkhurana** [Xilinx/PYNQ#1447]
I am getting 404 Page not found error message when I click on the supported multiple boards on the main page. The link takes me to this page: https://www.pynq.io/board.html

Can somebody please fix this?

**Comment by NireiSomu** [comment]
Try This https://www.pynq.io/boards.html

**Comment by mariodruiz** [comment]
Hi @jasvinderkhurana,

Can you please let me know where do you see the broken link?

**Comment by jasvinderkhurana** [comment]
The link is at [main page](https://github.com/Xilinx/PYNQ?tab=readme-ov-file) under **Precompiled Image** section see the link of [multiple boards](https://www.pynq.io/boards.html)
