### ISSUE TITLE
pmod_timer notebook and API

### ISSUE THREAD

**Issue by schelleg** [Xilinx/PYNQ#186]
@parimalp - can you beef up the pmod_timer python and notebook.  Some suggestions;

notebook
1. be explicit at the top that Analog discovery is needed.  
2. can you add screenshot perhaps of what analog discovery would show?  Otherwise, not too much visualization in here.

python
1. why is period=998 for 10ns period pulse?  If there is a -2 constant, can that be maintained inside python class?
2. pt.get_period_ns() hangs if nothing connected ... can you add timeout on calls?

**Comment by yunqu** [comment]
Fixed for item 1 from @schelleg.
