### ISSUE TITLE
wrong port in documentation

### ISSUE THREAD

**Issue by beja65536** [Xilinx/PYNQ#208]
In the documentation it says: http://pynq:8080 which should be 9090

another minor issue in addition: apostrophe missing at the end
0 : '640x480@60Hz
1 : '800x600@60Hz
2 : '1280x720@60Hz
3 : '1280x1024@60Hz
4 : '1920x1080@60Hz

**Comment by yunqu** [comment]
This has been fixed in the last few commits. So removing this from post-release tag.
