### ISSUE TITLE
MMIO write only supports int

### ISSUE THREAD

**Issue by yunqu** [Xilinx/PYNQ#212]
https://github.com/Xilinx/PYNQ/blob/master/python/pynq/mmio.py#L143

The write function does not support char or str write. Will have to support that.

**Comment by yunqu** [comment]
Has been fixed in a45549c

**Comment by manoharvhr** [comment]
How can I send floating-point numbers using MMIO?

**Comment by manoharvhr** [comment]
> How can I send floating-point numbers using MMIO?

https://groups.google.com/forum/#!searchin/pynq_project/MMIO$20$2B$20float|sort:date/pynq_project/yEw3d_2CVIs/aTYmnMLWAAAJ

works like charm!
