### ISSUE TITLE
Vivado TCL script fails in 2016.2

### ISSUE THREAD

**Issue by baronep** [Xilinx/PYNQ#223]
I guess the script was created in 2016.1. When I run "make" in Vivado I get the following error ...

[vivado.log.txt](https://github.com/Xilinx/PYNQ/files/543232/vivado.log.txt)

**Comment by yunqu** [comment]
Yes the script was created for Vivado 2016.1. For 2016.2, you can modify line 23 of base.tcl to:
```tcl
set scripts_vivado_version 2016.2
```

However, we have not tested this completely. But you should be able to build the bitstream.

**Comment by brad0taylor** [comment]
I'm having the same issue with 2016.3 and when I change the version I get the following error, which prevents me from rebuilding the bitstream.

> ERROR: [BD 5-216] VLNV <xilinx.com:ip:microblaze:9.6> is not supported for the current part. The latest supported version for this part is:10.0

**Comment by brad0taylor** [comment]
btw I'm not very familiar with the process here. Should I have opened a new issue about this?

**Comment by yunqu** [comment]
For 2016.2, you can also upgrade an existing project.

1.Unzip attached file and open project in Vivado (2016.2)
2.Upgrade IP when asked, and regenerate the bitstream
