### ISSUE TITLE
HDMI input fails with google chromecast input

### ISSUE THREAD

**Issue by brad0taylor** [Xilinx/PYNQ#225]
When I connect the PYNQ HDMI input to a google chromecast device, it appears to be capturing a blank/black screen. I'm using the 5_base_overlay_video.ipynb page for testing. It captures and displays video from my notebook fine.  Not sure if this is a configuration issue or perhaps its just not compatible, but I did want to record the issue.

**Comment by brad0taylor** [comment]
Also, the HDMI port does seem to work fine with my old Apple TV.

**Comment by plysaght** [comment]
You have got to love it when the new tech works with the older stuff, Brad

BTW Liam Madden just got his kit today so you are in good company

-P

**Comment by schelleg** [comment]
We have not seen fix for chromecast - I'll close for now, and put the help wanted label on here in case community wants to tackle this use case.
