### ISSUE TITLE
SDK TCL script fails in version 2016.3

### ISSUE THREAD

**Issue by LucaCerina** [Xilinx/PYNQ#230]
Hello,
xsdk build fails using vivado 2016.3 version with the following error 
`Note:: "build_project" command is Deprecated. Use "projects -build" command
unexpected arguments: all
    while executing
"error "unexpected arguments: $arglist""
    (procedure "::xsdb::get_options" line 69)
    invoked from within
"::xsdb::get_options args $options"
    (procedure "projects" line 12)
    invoked from within
"projects -build {*}$args"
    (procedure "::sdk::build_project" line 3)
    invoked from within
"sdk build all"
    (file "build_xsdk.tcl" line 16)
`
The generation of the Arduino and the Pmod bsp runs fine

**Comment by GuzTech** [comment]
I had the same problem. Remove the `all` from `sdk build all` in the `build_xsdk.tcl` file.
