### ISSUE TITLE
Vivado 2016.1 on Ubuntu 15.10 script generate multiple warnings

### ISSUE THREAD

**Issue by LucaCerina** [Xilinx/PYNQ#235]
Hi, I tried to generate the base bitstream using Vivado 2016.1, but it generates 17 critical warnings related to place and route and optimization, plus 746 general warnings (Log attached).
Is this dependent from the fact that Vivado 2016.1 is not fully supported on Ubuntu 15.10 (source UG973)?

Thanks

[vivado.txt](https://github.com/Xilinx/PYNQ/files/611527/vivado.txt)

**Comment by schelleg** [comment]
We have seen warnings in the past and build tests pass.  It could be due to OS support and let us know if any improvements to the Vivado flow.  I'll close for now.
