### ISSUE TITLE
Source files for png images

### ISSUE THREAD

**Issue by edowson** [Xilinx/PYNQ#248]
I'm working on adapting the PYNQ base overlay to support the ZC702, ZCU102 and TE-0723-02 boards.

Would it be possible to include the sources files for some of the png images located under docs/source/images, especially for the base overlay?

https://github.com/Xilinx/PYNQ/blob/master/docs/source/images/pynqz1_base_overlay.png

**Comment by yunqu** [comment]
[source.pptx](https://github.com/Xilinx/PYNQ/files/704904/source.pptx)

Is this okay?

**Comment by yunqu** [comment]
Is this okay?
[source.pptx](https://github.com/Xilinx/PYNQ/files/705079/source.pptx)

**Comment by edowson** [comment]
Yes,

It's just what I was looking for!

Regards,

Elvis Dowson
