### ISSUE TITLE
Can't run a simple Hello World stuff

### ISSUE THREAD

**Issue by pcotret** [Xilinx/PYNQ#277]
Hi,
I recently acquired a PYNQ board and I was trying to make a simple "hello world" program in a new Vivado project.

In Vivado, I only have my processing system with the UART configured.
When I want to run a default Hello World program in Xilinx SDK, I get the following error:

AP transaction error, DAP status f0000021

Any idea ?

**Comment by cathalmccabe** [comment]
Hi @pcotret 
Was this resolved with the correct PS settings?

**Comment by cathalmccabe** [comment]
This is resolved by using the correct board support files. e.g. Arty -Z20 https://github.com/Digilent/vivado-boards/archive/master.zip
Issue can be closed.
