### ISSUE TITLE
For loop typo in top.v

### ISSUE THREAD

**Issue by jgoeders** [Xilinx/PYNQ#464]
https://github.com/Xilinx/PYNQ/blob/b554fd00cbffd668d36b3f7e11d27e751d931580/boards/Pynq-Z1/base/vivado/top.v#L292

It looks like this for generate loop should go to 16, not 15.  I haven't tested anything on the board, but I would guess that IO41 might not be working properly because of this bug.

**Comment by parimalp** [comment]
Thank you for pointing out. We will fix this.

Regards,

Parimal
