### ISSUE TITLE
Edimax Wifi Dongle Fix Notebook

### ISSUE THREAD

**Issue by sgrace-xlnx** [Xilinx/PYNQ#465]
Hi Pynq Team!

Attached is a ipynb to go through the driver fix/update for the Pynq image (15.10 as of writing). It should really only be used by those that are not going to be running the latest image.

Please vet it, because talking with Graham, looks like newer images may not need this.

Thanks
Steve
[edimax_EW-7811Un_adapter_fix.zip](https://github.com/Xilinx/PYNQ/files/1354425/edimax_EW-7811Un_adapter_fix.zip)

**Comment by schelleg** [comment]
thanks Steve - we upgraded to 16.04 to resolve this
