### ISSUE TITLE
Place design Error (Implementation failed)

### ISSUE THREAD

**Issue by DevasenaInupakutika** [Xilinx/PYNQ#476]
Synthesises successfully but throws "place design error" during implementation when we source the base.tcl file. 

Could you please let me know what might be missing?

Error screenshots attached below:

![error-place-design](https://user-images.githubusercontent.com/538575/32456219-6807a8e2-c2ea-11e7-86e1-9a42d64dc891.png)
![error-place-design2](https://user-images.githubusercontent.com/538575/32456220-6818d27a-c2ea-11e7-9db5-b9c15120a873.png)

**Comment by yunqu** [comment]
The first thing that I have noticed, is that you are using Vivado 2016.2. The `base.tcl` on image v2.0 is verified and tested based on Vivado 2016.1, while there is no guarantee that the same tcl file will work for 2016.2. Is there a reason why you must use Vivado 2016.2?

Also, we are working on a new release which supports Vivado 2017.2.

Hope this helps.

**Comment by DevasenaInupakutika** [comment]
Thank you! There is no specific reason to use 2016.2. I had that installed on my system and have been working on either 2016.2 or 2016.4 of late, so tried with that version.  

That's great!

Also, ideally before reaching this implementation step, based on the condition in `base.tcl` file it should fail in the beginning itself (which it did). 

I changed the base.tcl script by making it run with 2016.2. It worked fine starting from sourcing the tcl files and building the PYNQ repository until Synthesis. 

The only reason I couldn't get is if it is version specific, it should fail initially even if I changed the tcl (one if condition block). 

Could you please comment or give input on this?

**Comment by yunqu** [comment]
https://github.com/Xilinx/PYNQ/blob/master/boards/Pynq-Z1/base/base.tcl#L76

We do have that checking. But if you tried to change the version number, that is almost like a hack, so it may fail...

**Comment by DevasenaInupakutika** [comment]
Ok, yeah! Thank you! It worked on 2016.1 version only.
