### ISSUE TITLE
Can not use pynq.lib.arduino.arduino_io.Arduino_IO

### ISSUE THREAD

**Issue by theangels** [Xilinx/PYNQ#488]
I tried to use pynq Arduino IO port, and wrote this code with the help of PYNQ API Document, but when I run the python code, it throwed an error "'Arduino' object has no attribute 'start'".

![image](https://user-images.githubusercontent.com/11308780/34077928-a7b435b6-e34a-11e7-8edb-10652c0d4796.png)

There is the reference.
http://pynq.readthedocs.io/en/v2.0/pynq_package/pynq.lib/pynq.lib.arduino.html#module-pynq.lib.arduino.arduino_io

**Comment by yunqu** [comment]
It should be fixed in https://github.com/Xilinx/PYNQ/commit/5654cccd33a9dc63bd74fa09904be6d32d4c2dbf
