### ISSUE TITLE
Small tcl parsing bug in pl.py

### ISSUE THREAD

**Issue by a1650078** [Xilinx/PYNQ#490]
While creating a minimal example for faster overlay testing, I tried to save time by using vivado's save/apply configuration function under the presets menu in ip configuration. This worked fine, but seems to add lines to the tcl for the block diagram. They look like this

`CONFIG.PCW_FCLK2_PERIPHERAL_DIVISOR1.VALUE_SRC {DEFAULT} \`

and the regex `clk_odiv_regex` picks them up and confuses the parser. Changing the line that tests the ignore regex to also skip if `"VALUE_SRC" in line` fixes it.

**Comment by yunqu** [comment]
Should be fixed in https://github.com/Xilinx/PYNQ/pull/491
