### ISSUE TITLE
Audio stream error in PYNQ

### ISSUE THREAD

**Issue by arkhodamoradi** [Xilinx/PYNQ#493]
In audio.py lines: 178 and 189 are causing error, gpio_pin is not initialized. I guess it is a leftover from the previous version and the code can be functional after commenting out those two lines.

**Comment by yunqu** [comment]
I am aware of this bug.
https://github.com/Xilinx/PYNQ/blob/master/pynq/lib/audio.py#L178

It will be fixed in the next release.
