### ISSUE TITLE
Getting Started Image / Text mismatch

### ISSUE THREAD

**Issue by drichmond** [Xilinx/PYNQ#496]
Someone pointed this out in class, but there are two issues in the getting_started.rst file: 

`To power the PYNQ-Z1 from the micro USB cable, set the **JP5 / Power**
jumper to the *USB* position by placing the jumper over the top two pins as
shown in the image. (You can also power the board from an external 12V
power regulator by setting the jumper to *REG*.)`

There are two problems: 

- The USB pins are actually the bottom two pins
- The REG pins are highlighted in the image (in blue)

**Comment by yunqu** [comment]
Thanks for pointing out. 

@cathalmccabe Can you update that page?
