### ISSUE TITLE
Way to get Zynq temperature by pynq package?

### ISSUE THREAD

**Issue by wtakase** [Xilinx/PYNQ#505]
Hello.
Is there any way to get Zynq chip temperature by using the pynq package?

**Comment by parthpower** [comment]
You can create an overlay which includes [XADC wizard](https://www.xilinx.com/support/documentation/ip_documentation/xadc_wiz/v3_0/pg091-xadc-wiz.pdf) IP and use the MMIO package of pynq to access the temperature register at offset of `0x200`

**Comment by wtakase** [comment]
Thanks!! I made it!!
