### ISSUE TITLE
general-purpose counters ——like NI DAQ

### ISSUE THREAD

**Issue by diamond2nv** [Xilinx/PYNQ#527]
[PYNQ/pynq/lib/pmod/pmod_timer/src/pmod_timer.c](https://github.com/Xilinx/PYNQ/blob/master/pynq/lib/pmod/pmod_timer/src/pmod_timer.c)

Could PYNQ had func of general-purpose counters ——like NI DAQ ?
Mostly for Single Photon Counting Module.

(:
Number of counter/timers： 4

Resolution： 32 bits

Counter measurements： Edge counting, pulse, pulse width,
period, two-edge separation...

Applications： Event counter, Count, Pulse, pulse train with dynamic updates,
frequency division, equivalent time sampling...

Input frequency: 0 MHz ~ 25 MHz (Floating Random)
Minimum high pulse width 10 ns  (Fixed)
）

**Comment by schelleg** [comment]
Yes please - we are working on some small counters with more IO functionality, but any help appreciated.

**Comment by schelleg** [comment]
I'll close this old issue - please check out the pynq forum for gathering ideas & collaborators: http://www.pynq.io/support.html
