### ISSUE TITLE
Arduino_io bug

### ISSUE THREAD

**Issue by rrajan8** [Xilinx/PYNQ#534]
https://github.com/Xilinx/PYNQ/blob/72b2e505e6a6a6a2cc77321d006a2c6fff65371a/pynq/lib/arduino/arduino_io.py#L97

https://github.com/Xilinx/PYNQ/blob/c971535a22f00e7b2e97ff9b388c423a0b35dbc4/pynq/lib/arduino/arduino_io.py#L116

When Arduino_IO is instantiated python fails at above two lines. Changing  self.microblaze.* to self.* in the above two lines fixes the issue. Have confirmed fix reads GPIO correctly.

**Comment by drichmond** [comment]
I helped confirm this

**Comment by yunqu** [comment]
Thanks. This will be fixed in the next release coming soon.
