### ISSUE TITLE
v2.1 iop reset signals

### ISSUE THREAD

**Issue by cathalmccabe** [Xilinx/PYNQ#548]
iop_arduino has s_axi_aresetn input port (this is a peripheral reset signal). There is also a local reset block which generates an equivalent reset signal. 
These resets are connected inconsistently to ports in the design. For example, S00 and S05 AXI channels use the s_axi_resetn, and the others, S01 - S04 use the internally generates peripheral_aresetn. 

For consistency, (and to prevent future problems) only one reset signal should be used.  for all IP in the same clock domain. 

For discussion: either remove the s_axi_aresetn input port and only use resets from the block inside this IOP, or add an interconnect reset port to the IOP and remove the local reset generator block. 

The reset generator also provides a port out of this IOP block for a peripheral reset which connects to a downstream AXI interconnect. This could also be removed, as an equivalent reset signal is available at that level of hierarchy in the design. 

pmod_iops have a similar issue.

**Comment by parimalp** [comment]
Good catch, however there is a reason for it. I took care of it in logictools overlay. In the base overlay, I forgot to clean it up.  The reason for two resets is there are couple of peripherals including shared mb_bram controller, intr_ack are controlled by A9 and so they should be connected to A9 controller reset blocks and clock domains. The rest of the ips in iop are controlled by iop_mb so it should have its own reset block. This way if someone changes the design with two different clock domains (currently we have all running at 100 MHz) they don’t run into issues.

I can make changes and update the tcl file in 24 hours… however, as I understand we have a design freeze for this release. If decided to make changes possible, I will do it today.

Regards,

Parimal
