### ISSUE TITLE
/sdbuild/scripts/setup_host.sh error in ubuntu 16.04

### ISSUE THREAD

**Issue by lxzheng** [Xilinx/PYNQ#582]
Run setup_host.sh will get the following error

E: Unable to locate package lib32bz2-1.0
E: Couldn't find any package by glob 'lib32bz2-1.0'
E: Couldn't find any package by regex 'lib32bz2-1.0'

It should use the package libbz2-1.0:i386 instead of the package  lib32bz2-1.0.

**Comment by schelleg** [comment]
upgraded to 18.04 - can reopen new issue if naming errors occur
