### ISSUE TITLE
Pynq v2.1 image

### ISSUE THREAD

**Issue by bgee1** [Xilinx/PYNQ#585]
I am having trouble getting the board to boot up with the v2.1 image on windows 10. The Done light turns on but LEDs 0-3 never turn on.

**Comment by yunqu** [comment]
Thanks for testing it out with Windows 10. Can you try to connect to USB terminal to see what error message? We need more information to identify the problem.

Btw, the first time it may take a little more time to boot up the board -- even longer for LEDs to flash.

**Comment by bgee1** [comment]
Here a screen shot of the boot-up sequence. I hope that helps.
![screenshot](https://user-images.githubusercontent.com/9601460/36688273-c5692d3c-1ae0-11e8-8389-ddcd9653ada8.png)

**Comment by yunqu** [comment]
Hi, can you try downloading the image again, unzip it properly, and burn you SD image card? Have you also tried using a different SD card?

**Comment by bgee1** [comment]
I downloaded the image again and this time everything worked. Not sure what happened the first time but thanks for your help!
