### ISSUE TITLE
Undefined reference in libsds_lib.so

### ISSUE THREAD

**Issue by HeroGian** [Xilinx/PYNQ#595]
Hi,
I need to use the library "libxlnk_cma.h" in my project. I have built the library PYNQ/sdbuild/packages/libsds/xlnkutils with the Makefile provided and "aarch64-linux-gnu-g++" compiler.
I have added the library directory in my project with -L flag and shared object file with -lsds_lib, but in linking phase I get the following errors:

_libsds_lib.so: undefined reference to `sds_alloc_cacheable(unsigned int)'
libsds_lib.so: undefined reference to `sds_mmap(void*, unsigned long, void*)'
libsds_lib.so: undefined reference to `sds_alloc_non_cacheable(unsigned int)'
libsds_lib.so: undefined reference to `cf_xlnk_open(int)'
libsds_lib.so: undefined reference to `sds_munmap(void*)'
libsds_lib.so: undefined reference to `sds_free(void*)'
libsds_lib.so: undefined reference to `xlnkGetBufPhyAddr(void*)'
libsds_lib.so: undefined reference to `add_sw_estimates'
collect2: error: ld returned 1 exit status
ERROR: [SdsCompiler 83-5019] Exiting sds++ : Error when calling 'aarch64-linux-gnu-g++_

Could you help me with this problem?

**Comment by yunqu** [comment]
Hi,

I think we are using arm-linux-gnueabihf-gcc instead of the 64-bit compiler you are referring to.

Thanks,

Rock

**Comment by schelleg** [comment]
ZU+ support coming, currently on the image_v2.3 branch.  @yunqu 's answer is correct
