### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by Clement25** [Xilinx/PYNQ#619]
I typed one command "sudo pip3.6 install git+https://github.com/Xilinx/BNN-PYNQ.git" to install the package of BNN. Firstly it cannot identify the host name so I add "192.30.255.112 github.com" to the host file /etc/hosts. 
When I run this command again, the error becomes "cannot connect to the server". How can I solve this?
I connect the board to the ethernet port on my laptop. My laptop has been connected to a WLAN without proxy. The version of PYNQ is the latest v2.1.

**Comment by cathalmccabe** [comment]
Your board needs to be connected to the internet to do this. If you connect to the Ethernet port of your laptop as described in the setup guide, you have a local network to your laptop only. (You can try to bridge your WiFi and Ethernet connection on your laptop, but I would not suggest you do this as it can be complicated.)

To resolve this, connect your board to a router, or network switch that can serve the board a DHCP address as described in the getting started guide.
http://pynq.readthedocs.io/en/v2.1/getting_started.html#ethernet-setup
You can then pip install.

Alternatively, download the BNN GitHub as a .zip file. Unzip, and copy to the board. You can then install locally by running:
 sudo pip3.6 install <local folder>

Please post any support questions to the forum: www.pynq.io/support
