### ISSUE TITLE
How to handle AXI master port?

### ISSUE THREAD

**Issue by Iceomj** [Xilinx/PYNQ#624]
Docs of PYNQ shows how to handle the AXILite and AXIStream, but no evidence how to deal with AXI master, someone know how to transfer data when I use m_axi port in the HLS code?

**Comment by cathalmccabe** [comment]
This is a HLS question, not PYNQ specific. You can find some examples in the Vivado HLS tools and on the Xilinx forum on how to do this. From PYNQ, you just need to make sure you allocate memory for the HLS IP to use. You can do this using Xlnk(). http://pynq.readthedocs.io/en/v2.1/overlay_design_methodology/pspl_interface.html#xlnk
Please post further PYNQ questions on the PYNQ forum http://www.pynq.io/support.html, and Xilinx questions on the Xilixn forums https://forums.xilinx.com
