### ISSUE TITLE
Support for ADALM-PLUTO

### ISSUE THREAD

**Issue by bogdanr** [Xilinx/PYNQ#642]
It would be really nice if we can use this with ADALM-PLUTO.
I guess it shouldn't be hard to achieve this but a guide for beginners could definitely help.

**Comment by gpcus** [comment]
I ported PYNQ 2.1 SD to a custom zynq-based board, you may have a look and see if this thread helps you:
https://groups.google.com/forum/#!topic/pynq_project/e6Fr2del9Ig

**Comment by schelleg** [comment]
I'll close the issue - for broader community support, check out http://www.pynq.io/support.html.  Some users have ported to various boards.
