### ISSUE TITLE
libgnutls-dev renamed to libgnutls28-dev

### ISSUE THREAD

**Issue by drichmond** [Xilinx/PYNQ#666]
It looks like libgnutls-dev, which is installed in setup_host.sh was renamed to libgnutls28-dev in newer versions of Ubuntu.

**Comment by bobwmcgrath** [comment]
I just edited setup_host.sh

**Comment by yunqu** [comment]
I think this error might be related to the use of ubuntu 18.04 VMs. I have been using the original `setup_host.sh` and there seems no problem.
