### ISSUE TITLE
PYNQ update issue

### ISSUE THREAD

**Issue by aniqurrehman** [Xilinx/PYNQ#668]
while updating pynq i am getting this error.

fatal: unable to access 'https://github.com/Xilinx/PYNQ.git/': Could not resolve host: github.com
Command "git clone -q https://github.com/Xilinx/PYNQ.git /tmp/pip-dw4yjj8f-build" failed with error code 128 in None

i am using follwing command to update.
sudo pip3.6 install --upgrade git+https://github.com/Xilinx/PYNQ.git

**Comment by aniqurrehman** [comment]
yes i am connecting my board to ethernet and i am also able to install other packages but reciveing error for this command.

**Comment by aniqurrehman** [comment]
i am unable to install any package from git.

**Comment by yunqu** [comment]
I think you must have installed git again on your board. The PYNQ image comes with git so you do not need to do that. I am not sure how to recover the original version but a simple solution could be re-image the sd card.

**Comment by aniqurrehman** [comment]
no i haven't installed git again.
foolwing is the output for traceroute github.
![image](https://user-images.githubusercontent.com/15038246/42954178-86b2346e-8b95-11e8-8f99-0329f1d2ac76.png)

**Comment by yunqu** [comment]
Is it possible that you are behind a proxy?

**Comment by aniqurrehman** [comment]
yes i am behind a proxy but i set the git proxy  and system proxy but still its not working 

![image](https://user-images.githubusercontent.com/15038246/42988625-c2d90054-8c16-11e8-85a1-1c54be7e5737.png)

**Comment by aniqurrehman** [comment]
when i ping the proxy server it says network is unreachable.

**Comment by yunqu** [comment]
did you try;

```python
export http_proxy=https://your_proxy:your_port
export https_proxy=http://your_proxy:your_port
```

**Comment by aniqurrehman** [comment]
yes i tried that at that time i was behind proxy and it was not working now i left the proxy network and using another network and remove all proxies from github and system but now getting this error. i am stucked and don't know what to do with this . i've tried every method. but its not working.
![image](https://user-images.githubusercontent.com/15038246/43039357-fc9d79ee-8d44-11e8-8452-7e8553d7bb46.png)

**Comment by drichmond** [comment]
Can you post the output of running `env`?

**Comment by aniqurrehman** [comment]
BOARD=Pynq-Z1
XDG_SESSION_ID=c1
PYNQ_PYTHON=python3.6
SHELL=/bin/bash
TERM=vt220
HUSHLOGIN=FALSE
LC_ALL=en_US.UTF-8
USER=xilinx
RESIZED=1
MAIL=/var/mail/xilinx
PATH=/opt/sigrok/bin:/opt/sigrok/bin:/opt/microblazeel-xilinx-elf/bin:/opt/python3.6/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
PWD=/home/xilinx
LANG=en_US.UTF-8
SHLVL=1
HOME=/home/xilinx
LOGNAME=xilinx
PYNQ_JUPYTER_NOTEBOOKS=/home/xilinx/jupyter_notebooks
XDG_RUNTIME_DIR=/run/user/1000
_=/usr/bin/env

**Comment by drichmond** [comment]
Okay, nothing there looks worrisome. 

Are you able to ping github?

**Comment by aniqurrehman** [comment]
yes i can ping github

**Comment by aniqurrehman** [comment]
i have removed git and reinstall it but it didin't worked.

**Comment by drichmond** [comment]
What about `sudo env`?

**Comment by aniqurrehman** [comment]
i reinstall the image now the issue is resolved.
