### ISSUE TITLE
Build xlnk Driver Lib for cross_compile

### ISSUE THREAD

**Issue by joyliu37** [Xilinx/PYNQ#676]
Hi, I am wondering could I install the <libxlnk_cma.h> library in "/sdbuild/packages/libsds/xlnkutils" on my x86 server and cross compile host code from it. I try to use the Makefile directly but it keep giving me the following error. Could you give me some guide? Thanks a lot.

gcc -shared -rdynamic -o libsds_internal.so -Wl,--whole-archive libsds_lib_64.a -Wl,--no-whole-archive
/usr/bin/ld: libsds_lib_64.a(sds_lib.o): Relocations in generic ELF (EM: 183)
libsds_lib_64.a(sds_lib.o): error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
Makefile:11: recipe for target 'libsds_internal.so' failed
make: *** [libsds_internal.so] Error 1

**Comment by schelleg** [comment]
that code is compiled for arm/aarch64, so wouldn't work on x86.
