### ISSUE TITLE
Removing the Bitstream form PL

### ISSUE THREAD

**Issue by ussamazahid96** [Xilinx/PYNQ#708]
Hi,

Is it possible to remove bitstream from the PL without rebooting PYNQ? whenever I want to upload a new bitstream I have to reboot PYNQ, Otherwise new bitstream didn't actually get loaded and PL shows the results of the previous bitstream.

Thanks!

**Comment by cathalmccabe** [comment]
Please post this on the support forum (with a code example): http://pynq.io/support

**Comment by schelleg** [comment]
I'll close if this is moving out to the forum
