### ISSUE TITLE
How encrypt a bitstream file?

### ISSUE THREAD

**Issue by ileop** [Xilinx/PYNQ#739]
Hi, 
is it possible to encrypt a Bitstream file and still being able to use it as an overlay?
In the case, may you provide some hint on how to can do it, please?

Thank you

**Comment by cathalmccabe** [comment]
Yes, this should be possible but it is largely orthogonal to PYNQ. Once you encrypt the bitstream, you should be able to download it with the PYNQ _Overlay_ class.

**Comment by giunatale** [comment]
Hi @ileop, I see your question was already answered. If you are still not satisfied, I need to kindly ask you to redirect your question to our forum: https://discuss.pynq.io
That's the dedicated place to receive support from the community.
The issue tracker here is to report bugs in the codebase.

Closing this now, thanks in advance for your collaboration.
