### ISSUE TITLE
Can not read HDMI IN

### ISSUE THREAD

**Issue by SmaleZ** [Xilinx/PYNQ#740]
My pynq_z2 can read HDMI signals from the laptop, but cannot read HDMI signals from the AV2HDMI converter. 
When it is running, the program will be stuck.
But after connecting the HDMI output of the laptop to the HDMI input and displaying normally, the signal obtained by the AV2HDMI converter can be displayed, but the resolution is wrong.
Whether this is related to the HDMI handshake protocol?

**Comment by giunatale** [comment]
Hi @SmaleZ, I need to kindly ask you to redirect your question to our forum: https://discuss.pynq.io
That's the dedicated place to receive support from the community.
The issue tracker here is to report bugs in the codebase.

Closing this now, thanks in advance for your collaboration.
