### ISSUE TITLE
setup_host.sh fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by tranzmatt** [Xilinx/PYNQ#741]
Is there a preferred build environment for 2.3?  For my own learning purposes, I'm trying to build the sdcard from the git source, but setup_host.sh fails in numerous places:

E: Package 'libgnutls-dev' has no installation candidate

changing to libgnutls28-dev resolves that, but then I get:

```
In file included from zconf.tab.c:212:0:
zconf.hash.c:167:1: error: conflicting types for ‘kconf_id_lookup’
 kconf_id_lookup (register const char *str, register size_t len)
 ^~~~~~~~~~~~~~~
zconf.hash.c:34:31: note: previous declaration of ‘kconf_id_lookup’ was here
 static const struct kconf_id *kconf_id_lookup(register const char *str, register unsigned int len);
                               ^~~~~~~~~~~~~~~
Makefile:88: recipe for target 'zconf.tab.o' failed
make[2]: *** [zconf.tab.o] Error 1
Makefile:167: recipe for target 'build-lib-kconfig' failed
make[1]: *** [build-lib-kconfig] Error 2
Makefile:127: recipe for target 'build' failed
make: *** [build] Error 2
```

when crosstool-ng-1.22.0.tar.bz2 tries to compile.  Updating to crosstool-ng-1.23.0 resolved this compile issue, but are there other things that could cause problems?

**Comment by yunqu** [comment]
The preferred environment is Ubuntu 16.04; I am not sure if petalinux 2018.2 supports ubuntu 18.04  nicely so it would be better to use 16.04.
