### ISSUE TITLE
wifi module

### ISSUE THREAD

**Issue by lyn2333** [Xilinx/PYNQ#746]
Hi,
  I have a question that after the WiFi module is connected,  can I transmit files to the board through WiFi?  If possible, where will the document be placed?

**Comment by cathalmccabe** [comment]
Please post questions to the support forum: http://www.pynq.io/support.html
The PYNQ image is based on Ubuntu. With WiFi or wired Ethernet you can copy files to the board as you would for any Ubuntu based computer. 
You can use Samba, ssh/ftp etc, or upload files via Jupyter. With the first methods, you can upload files and where to the filesystem (which is stored on the SD card). With Jupyter, yuou upload files to the jupyter_notebook folder and sub folders.
