### ISSUE TITLE
the pynq dma can't support Single channel mode

### ISSUE THREAD

**Issue by hisrg** [Xilinx/PYNQ#750]
if i set DMA as below picture. it can't work and find a error.
![1](https://user-images.githubusercontent.com/21289177/47984508-c922e100-e111-11e8-9c4c-442c69411bca.png)
![2](https://user-images.githubusercontent.com/21289177/47984509-c922e100-e111-11e8-81b7-10816c199919.png)
could you tell me how to solve it?

**Comment by PeterOgden** [comment]
The dma object appears to have the wrong driver allocated to it. Can you post the full notebook so I can have a better look?

**Comment by hisrg** [comment]
![1](https://user-images.githubusercontent.com/21289177/48038373-46e6fb00-e1ab-11e8-8bb8-dbfbd2765986.png)
![2](https://user-images.githubusercontent.com/21289177/48038374-46e6fb00-e1ab-11e8-977c-f89b9d878304.png)
![3](https://user-images.githubusercontent.com/21289177/48038376-477f9180-e1ab-11e8-9960-404ec58dcdcb.png)

note: the bit file has changed so that report error as above when i reply this issue, you can use pynq tutorial2's bd file to generate bit and tcl file to overlay in this notebook, but it needs you setup the DMA  config as 1st figure. thanks.

**Comment by PeterOgden** [comment]
The `bindto` statement in your ConstantMultiplyDriver is wrong - it's currently binding to the DMA engine which is not what you want. Given that you are not using that IP any longer I would just remove the driver and restart the notebook.

**Comment by hisrg** [comment]
thanks

**Comment by hisrg** [comment]
![image](https://user-images.githubusercontent.com/21289177/48936135-e7c40d00-ef44-11e8-83c3-69dac484f85a.png)
 how to write this DMA drvier as above bd? which produce some data from PL(1),and then writes in FIFO(2), Finally it will display in Jupyter notebook.  i think it trans data from PL to PS using singal DMA channel and interrupt.

**Comment by yunqu** [comment]
There are many examples online. For example:
https://github.com/Xilinx/PYNQ-DL/blob/master/notebooks/resize.ipynb
https://github.com/yunqu/PYNQ-derivative-overlays/tree/master/sdx_platform#porting-onto-pynq

By the way, your S_AXIS should not be an input port, it should connect to another DMA back to PS, or another channel of your block 2. That way you have a complete loop.

**Comment by giunatale** [comment]
Hi @hisrg, I see your question has been already extensively answered. If you are still not satisfied, I need to kindly ask you to redirect your question to our forum: https://discuss.pynq.io
That's the dedicated place to receive support from the community.
The issue tracker here is to report bugs in the codebase.

Closing this now, thanks in advance for your collaboration.
