### ISSUE TITLE
Add dependencies in the Makefile so it can run in parallel.

### ISSUE THREAD

**Issue by Olangu** [Xilinx/PYNQ#757]
Currently the system will only produce correct results with one thread.

If dependencies and non parallelization arguments would be added to the Makefile one could make use of multiple threads with ```make -j4``` or ```make -j$(nproc)```.

This would greatly increase build speed on modern systems (our build server have 12 cores) and would likely bring down build times to under the hour, instead of "several hours" as the Readme states.

**Comment by PeterOgden** [comment]
Many of the sub-stages of the Makefile will already run in parallel - the PetaLinux and cross-tools sections will already use as many cores as are available so building those in parallel at the top level will probably not improve performance that greatly. The parts inside QEMU are more challenging as many of the underlying tools we use won't tolerate being invoked multiple times simultaneously. In particular a lot of time is spent running PIP which takes a global lock when working. All of these sections are also inherently sequential in the Makefile - we can't run stage 2 before stage 1 has finished.

All that being said, make not running correctly implies an error in our dependencies which should probably be fixed. I'm just wary that there may always be some issues with say PetaLinux that precludes the use of the `-j` option without explicitly serialising everything.
