### ISSUE TITLE
Some questions about using Pynq xlnk.

### ISSUE THREAD

**Issue by clancylea** [Xilinx/PYNQ#761]
I'm a pynq user, i have some questions when using pynq .
I allocated memory by pynq xlnk() like Figure(1), and send the physical address to the linux application, which use mmap() function to remap the physical address. But the result was wrong.
Before this, i used Zedborad with half memory for Linux and half for PL(Because Zedboard only has 512MB memory, so memory from 0x1000000 to 0x1FFFFFFF are used by PL), using mmap() to remap physical address above 0x10000000,
 and the result was right.
I didn't get the key to find where's the problem, can you give me some advice? Thanks!

![figure 1](https://user-images.githubusercontent.com/42167380/48548763-bf1a9280-e908-11e8-96b0-26fad1393ea6.jpg)

**Comment by cathalmccabe** [comment]
What are you trying to do? Xlnk allocates contiguous memory in the Linux memory system, and gives the virtual address and the corresponding physical address. Why are you trying to remap the memory from Linux? You can already access this memory from Linux using the virtual address.

**Comment by giunatale** [comment]
Hi @clancylea, I see your question was already answered. If you are still not satisfied, I need to kindly ask you to redirect your question to our forum: https://discuss.pynq.io
That's the dedicated place to receive support from the community.
The issue tracker here is to report bugs in the codebase.

Closing this now, thanks in advance for your collaboration.
