### ISSUE TITLE
bnn installation problem

### ISSUE THREAD

**Issue by aysegulucar2016** [Xilinx/PYNQ#769]
Why Cant I instal bnn? I used ubuntu also. I received similar errors with 128 code in Ubuntu too. could you immediately please support me?

![2018-12-01_11-04-04-c7002ccfe371dbd2516c8c9147b24ac0](https://user-images.githubusercontent.com/16757934/49606866-90db2080-f9a5-11e8-85a2-a2cee61d4259.png)

fatal: unable to access 'https://github.com/Xilinx/BNN-PYNQ.git/': Could not resolve host: github.com
Command "git clone -q https://github.com/Xilinx/BNN-PYNQ.git /tmp/pip-x6y_ng81-build" failed with error code 128 in None

**Comment by xupsh** [comment]
You need to make sure your pynq board can connect to the network. Just have a try using `ping github.com`

**Comment by aysegulucar2016** [comment]
it is unreachable.

**Comment by yunqu** [comment]
The command should be:
```shell
pip3 install --upgrade git+https://github.com/Xilinx/BNN-PYNQ.git 
```

Try to first do git clone to see whether your network has a problem or not.
