### ISSUE TITLE
update problem of pynq

### ISSUE THREAD

**Issue by aysegulucar2016** [Xilinx/PYNQ#771]
ilinx@pynq:~$ sudo apt-get update
[sudo] password for xilinx: 
Err:1 http://ports.ubuntu.com/ubuntu-ports bionic InRelease
  Temporary failure resolving 'ports.ubuntu.com'
Reading package lists... Done
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/bionic/InRelease  Temporary failure resolving 'ports.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by xupsh** [comment]
Seems to be network error. Have a try to `ping ports.ubuntu.com` to see if the network is ok.

**Comment by hustjinghu** [comment]
How to discover the pynq version in the linux shell?

**Comment by hustjinghu** [comment]
Dear xupsh , i have ping ports.ubuntu.com,but the following results shows. However,i ping 192.168.2.99, it shows my PC can connect to PYNQ-Z2 board, my PC can connecte to internet.
![image](https://user-images.githubusercontent.com/12193928/50574001-c561c100-0e19-11e9-9d1a-d0e81c5421bb.png)
