### ISSUE TITLE
pip3 install problem

### ISSUE THREAD

**Issue by chiayilin1991** [Xilinx/PYNQ#776]
My board is pynq-z2.
And, I tried to pip3 install git+https://github.com/Xilinx/QNN-MO-PYNQ.git, 
but there was no any response after cloning.

Collecting git+https://github.com/Xilinx/QNN-MO-PYNQ.git
  Cloning https://github.com/Xilinx/QNN-MO-PYNQ.git to /tmp/pip-bl5011_8-build

I had  waited for about 20min.
By the way, I could ping github.com.

**Comment by yunqu** [comment]
I think this is network issue. I don't know what your setup is, but I suggest you have a look at the troubleshooting page: https://pynq.readthedocs.io/en/latest/faqs.html
