### ISSUE TITLE
Can't build pynq-z2 image

### ISSUE THREAD

**Issue by jihye0005** [Xilinx/PYNQ#792]
Hi! 

An error occurred while creating pynq image as shown below.

What should I do ?
Help me please~!

![image](https://user-images.githubusercontent.com/25446103/51591235-d2ad2f80-1f2f-11e9-8ecd-0c28e6d6bbb7.png)

**Comment by yunqu** [comment]
Maybe you can do a `make clean` before you rerun the make?
