### ISSUE TITLE
Build Scripts reference es2 board

### ISSUE THREAD

**Issue by AEW2015** [Xilinx/PYNQ#793]
The HLS build script.tcl for color_convert_2, pixel_pack_2, pixel_unpack_2 all reference the xczu7ev-ffvc1156-2-i-es2 board.
This is an engineering sample and not included in the normal license.
I removed the es2 off the end and used that to build the overlay for the zcu104.

**Comment by yunqu** [comment]
Thanks for the notice. Yes we are aware of this issue, and it should be fixed in https://github.com/Xilinx/PYNQ/pull/775
