### ISSUE TITLE
Fail to boot with pynq Z2

### ISSUE THREAD

**Issue by kfeng123** [Xilinx/PYNQ#794]
I use a new PYNQ Z2 board. Use the default linux in SD card. And I follow the official site. I can successfully connect my PC with the board using USB. But the linux can not  boot and there seems no error hint. It says:

> u-boot 2018.07-00001-ge2382ce (Apr 24 2008 - 12:12:31 -0600)
> 
> Model: Zynq ARTY 27 Development Board
> Board: Xilinx Zynq
> I2C: ready
> ....(I ignore some lines which contain no error)
> Importing envirenment from mmc ...
> Checking if uenvcmd is set ...
> Hit any key to stop autoboot: 3

After I hit any key, the zynq prompt appears. 

Please help me. I am desperate. Any hint is greatly appreciate!

**Comment by cathalmccabe** [comment]
Please post support questions on the forum: http://www.pynq.io/support.html This is probably a power issue.
