### ISSUE TITLE
[Pynq-Z2] Add Uart1

### ISSUE THREAD

**Issue by jihye0005** [Xilinx/PYNQ#801]
Hi! I'm using Pynq-Z2 board.

I have a question.
I have found uart1 in the device tree file.
How do I activate this uart1?

Should I rebuild the image,
Or can I just upload a driver?

Please tell me how to do it~~!!

![image](https://user-images.githubusercontent.com/25446103/51965300-6b9df680-24ac-11e9-8f48-a8e890527615.png)

**Comment by cathalmccabe** [comment]
Can you please post this to the support forum: http://www.pynq.io/support.html ?

**Comment by jihye0005** [comment]
Absolutely! Thank you~
