### ISSUE TITLE
Compile kernel with different configuration

### ISSUE THREAD

**Issue by LanderU** [Xilinx/PYNQ#823]
Hello!

I would like to know which is the best option to compile a kernel enable/disable some configurations.

I try it out using the kernel that comes with the SD Card. I getting the following error:

```bash
4405904 bytes read in 254 ms (16.5 MiB/s)
## Booting kernel from Legacy Image at 10000000 ...
   Image Name:   Linux-4.14.0-xilinx-v2018.2
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    4405840 Bytes = 4.2 MiB
   Load Address: 10000000
   Entry Point:  10000000
   Verifying Checksum ... OK
   Loading Kernel Image ... OK
FDT and ATAGS support not compiled in - hanging
### ERROR ### Please RESET the board ###
```

Thanks in advance!

**Comment by giunatale** [comment]
Hi @LanderU, I need to kindly ask you to redirect your question to our forum: https://discuss.pynq.io
That's the dedicated place to receive support from the community.
The issue tracker here is to report bugs in the codebase.

Closing this now, thanks in advance for your collaboration.
