### ISSUE TITLE
Cannot find sds_lib on Pynq

### ISSUE THREAD

**Issue by riple** [Xilinx/PYNQ#828]
I am trying to compile some c++ program locally on Pynq 2.4, and I ran into this:

/usr/bin/arm-linux-gnueabihf-ld: cannot find -lsds_lib
collect2: error: ld returned 1 exit status

The command I am running is
g++ -std=c++11 *.cpp -lsds_lib -o app

**Comment by riple** [comment]
I am using the rootfs from
https://www.xilinx.com/member/forms/download/xef.html?filename=pynq_rootfs_arm_v2.4.zip

**Comment by yunqu** [comment]
This has been changed to libcma.so so you need to use `-lcma` instead.
