### ISSUE TITLE
fpga_manager fpga0: Error while writing bin data to FPGA with Ultra96 

### ISSUE THREAD

**Issue by hablu** [Xilinx/PYNQ#831]
The error is kind of similar to the #767 but as it has been closed, and my board is different, I am creating this new issue.

![image](https://user-images.githubusercontent.com/15050233/54504892-da9db480-495f-11e9-8515-4b152b02a959.png)
I am facing some error while trying to write a bin file to my Ultra96 board.
I have been using the board image (Avnet Ultra96 v2.4 PYNQ image) from here: 
![image](https://user-images.githubusercontent.com/15050233/54504954-146ebb00-4960-11e9-9a5f-d07ac9c583a8.png)
Can you please tell me how can I solve it? Thanks.

**Comment by yunqu** [comment]
Try to provide an absolute path for your bitstream. This is a different issue than #767 where a customized image needs to be built.

**Comment by giunatale** [comment]
Hi @hablu, I see your question was already answered. If you are still not satisfied, I need to kindly ask you to redirect your question to our forum: https://discuss.pynq.io
That's the dedicated place to receive support from the community.
The issue tracker here is to report bugs in the codebase.

Closing this now, thanks in advance for your collaboration.
