### ISSUE TITLE
Looking for Pmod Grove RTC example code

### ISSUE THREAD

**Issue by mahdiunh** [Xilinx/PYNQ#832]
Hello,

I have got a Pmod Grove RTC device which I hoped to be able to use it the same way I have been using my Pmod Grove IMU (using the example C code that is provided on this repository), however I noticed there is no such example code for the Grove RTC. I am aware of the Arduino and python scripts that are available on Grove RTC webpage, but due to some limitations I need to use it the same way I am using my Grove IMU device (which is using it with PYNQ board). Does anybody know if there is such example code written in C language for this device out there? It seems to be a simple I2C device, however I have not had luck writing my own script for it by following the examples of other I2C devices.

Best,
Mahdi

**Comment by giunatale** [comment]
Hi @mahdiunh, I need to kindly ask you to redirect your question to our forum: https://discuss.pynq.io
That's the dedicated place to receive support from the community.
The issue tracker here is to report bugs in the codebase.

Closing this now, thanks in advance for your collaboration.
