### ISSUE TITLE
pynqz1_base_overlay.rst Spelling

### ISSUE THREAD

**Issue by mdkling** [Xilinx/PYNQ#836]
File: pynqz1_base_overlay.rst

Issue: Spelling of "Arduino" on Line 134

```
134  |  -  |  The PYNQ-Z1 has two types of PYNQ MicroBlaze: *Pmod* and *Arduio*, connecting
134  |  +  |  The PYNQ-Z1 has two types of PYNQ MicroBlaze: *Pmod* and *Arduino*, connecting
```

**Comment by schelleg** [comment]
Hi @mdkling - thanks for finding that.   You can PR that onto master if you want or I can commit it directly.

**Comment by schelleg** [comment]
Can I reopen and accept the Pull-Request?  Not sure if you closed it by mistake...

**Comment by mdkling** [comment]
I had to sign the CLA, it should be good now
