### ISSUE TITLE
KeyboardInterrupt dma.sendchannel.wait()

### ISSUE THREAD

**Issue by HungSoma** [Xilinx/PYNQ#846]
Hi,
Im trying to use DMA to tranfer an image to crop function but when dma.sendchannel.wait(), kernel always excute and I interupt it that error appear. 
Pls help me !
Thanks all!
![image](https://user-images.githubusercontent.com/29880226/55746247-730ced80-5a63-11e9-9041-010c0cbc0381.png)
![image](https://user-images.githubusercontent.com/29880226/55746288-8a4bdb00-5a63-11e9-9970-92532129a01a.png)
![image](https://user-images.githubusercontent.com/29880226/55746335-a3548c00-5a63-11e9-99a0-f16305540d8d.png)
![image](https://user-images.githubusercontent.com/29880226/55746375-bb2c1000-5a63-11e9-92ab-00ff7aee7de9.png)

**Comment by yunqu** [comment]
What is the size of `x`? Also, it looks like your `in_buffer` is 640x480x3 while your instantiate DMA buffer as 640x427x3. Not sure if this is going to be a problem.

**Comment by HungSoma** [comment]
x.size = ( 427, 640 ). I changed to dma.sendchannel.wait_async and dma.recvchannel.wait_async and it work  but result not as expect:
![image](https://user-images.githubusercontent.com/29880226/55773254-f0634d00-5ab9-11e9-8b7a-c057a293a634.png)
what  is the different between dma.sendchannel.wait() and dma.sendchannel.wait_async() ?

**Comment by giunatale** [comment]
Hi @HungSoma, I see your question was already answered. If you are still not satisfied, I need to kindly ask you to redirect your question to our forum: https://discuss.pynq.io
That's the dedicated place to receive support from the community.
The issue tracker here is to report bugs in the codebase.

Closing this now, thanks in advance for your collaboration.
