### ISSUE TITLE
Vagrant VM missing packages for Petalinux

### ISSUE THREAD

**Issue by kaofishy** [Xilinx/PYNQ#848]
Hi,

Following the instruction to bring up the PYNQ vagrant build environment, I was able to install Vivado inside the VM but encountered the following error while trying to install Petalinux 2018.3:

```
INFO: Checking installation environment requirements...
INFO: Checking free disk space
INFO: Checking installed tools
ERROR: You are missing the following system tools required by PetaLinux:

 - chrpath
 - socat
 - gcc-multilib
 - libsdl1.2-dev
Please check PetaLinux installation guide - required tools and libraries package section for detailed information

INFO: Checking installed development libraries
ERROR: You are missing these development libraries required by PetaLinux:

 - zlib1g:i386

Please install them with your operating system package manager, and try again
WARNING: Please install required packages.
```

Installing the required packages resolves the error.

I also found that `zlib1g:i386` requires `dpkg --add-architecture i386` followed by `apt update` otherwise you will get a package not found error.

Tony

**Comment by giunatale** [comment]
I believe this got fixed.

Closing this now.
