### ISSUE TITLE
Pynq Z-1, notebook crash whenn calling dma

### ISSUE THREAD

**Issue by mukechiltmal** [Xilinx/PYNQ#853]
Hey there,
i have been browsing for quite some and still havent found a solution to my issue
The system i use is the following:
Pynq Z1 with v2.4 image
A custom overlay with base overlay as template
as target system the pynq z1 board files

now to my issue:
In my overlay i am trying to use a dma to stream data from ps to an accelerator in pl and after processing back to ps
whenever i want to create an object of the said dma in the jupiter notebook, the system gets stuck/ crashes and requires a hard reset

here my DMA setup in vivado

![Screenshot (1)](https://user-images.githubusercontent.com/48212667/57009098-db7b6480-6bf4-11e9-8c85-8e5a0e27735b.png)

a screenshot of the dma part of the block design

![Screenshot (2)](https://user-images.githubusercontent.com/48212667/57009150-2b5a2b80-6bf5-11e9-9e77-56c9034d8061.png)

the used notebook

![Zwischenablage01](https://user-images.githubusercontent.com/48212667/57009299-0914dd80-6bf6-11e9-8898-cbd8b8ebeff8.jpg)

for anymore information let me know,

thanks
mukechiltmal

**Comment by cathalmccabe** [comment]
Can you post to the support forum please? 
http://www.pynq.io/support.html

**Comment by mukechiltmal** [comment]
sure, was waiting to get access xD
Closed
