### ISSUE TITLE
Audio record sample rate per word is not 192000

### ISSUE THREAD

**Issue by Larspolo** [Xilinx/PYNQ#862]
In the documentation of pynq.lib.audio, it states: "The sample rate per word is 192000Hz.". However, this is not always the case. When `self.sample_rate = num_samples_32b / (end - start)` is run, this rate is variable (for me between 195300 and 1953010). This makes the record function record shorter audio samples than expected. 

I would suggest using `self.sample_rate` (if set by a previous recording) in the `num_samples_32b` calculation. This does not make it perfect, but come closer to the actual record value than a hardcoded `192000`.

**Comment by cnSchwarzer** [comment]
Hi, 
I have the same situation.
According to my measurement, on Pynq-Z2, the ADAU1761 samples around 48740Hz, 1.6% error comparing to the standard. And the above situation is 195300 or 195310, which is also around 1.6%, so I believe we have the same problem.
This is annoying, so I wish you can fix this frequency error.
Thank you!
