### ISSUE TITLE
Is it possible to migrate PYNQ without sds?

### ISSUE THREAD

**Issue by zYeoman** [Xilinx/PYNQ#868]
For example, migrate a PYNQ for CPU&FPGA that communicate with each other by PCIe, not by shared memory.

**Comment by giunatale** [comment]
Hi @zYeoman, I need to kindly ask you to redirect your question to our forum: https://discuss.pynq.io
That's the dedicated place to receive support from the community.
The issue tracker here is to report bugs in the codebase.

Closing this now, thanks in advance for your collaboration.
