### ISSUE TITLE
any update for 2019.1 ?

### ISSUE THREAD

**Issue by thinkpiece** [Xilinx/PYNQ#871]
Hi, there.

Currently this repository refers to v2018.3 tools and seems out of date.

Do you have any plan for updating for v2019.1?
Or is it okay to revise the two environment variables, $KERNEL_VERSION and $LINUX_VERSION, in Makefile ?

Thanks

**Comment by giunatale** [comment]
Updates to latest Xilinx tools are always part of new releases. Next release (v2.5) will most likely be updated to support 2019.1.
Closing this for now.

Please, next time use our support forum https://discuss.pynq.io/ to ask these kind of questions. The github issue tracker is meant for reporting technical issues with the current code base.

Best,
Giuseppe
