### ISSUE TITLE
Is it possible to use XRT on Pynq?

### ISSUE THREAD

**Issue by tianhaoz95** [Xilinx/PYNQ#878]
Hi! Thanks for the awesome Pynq project! It's super fun to play with. I am wondering if it is possible to run XRT on the ARM in Pynq boards or is there any plan to enable it. I noticed that [Python XRT binding](https://github.com/Xilinx/XRT/tree/master/src/python) is already checked in as part of XRT. Is it possible to implement a Pynq driver module in XRT and enable both the "notebook" workflow and a much lower level "acceleration" workflow to experiment with potential implementations on much larger FPGAs?

**Comment by giunatale** [comment]
Hi @tianhaoz95, that is a great question. That is something we are already considering, follow the project and you'll definitely see more coming.

As this is a discussion point, I will close it now. We intend the issue tracker to be used to report bugs in the code base. For similar questions, in the future I need to kindly ask you to use our forum: https://discuss.pynq.io
That's the dedicated place to receive support from the community and have discussions like this one.
