### ISSUE TITLE
Unable to install Pynq python libraries with command

### ISSUE THREAD

**Issue by shravan-red** [Xilinx/PYNQ#899]
In order to add python code so as to output image through my zedboard's HDMI out, it seems, I need to install the hdmi module . And, as instructed on pynq official website, to install all pynq libraries, which I asssumed would include HDMI, I ran the command **_sudo pip3 install --upgrade git+https://github.com/Xilinx/PYNQ.git_** and I got an error as follows :
_Command "git clone -q https://github.com/Xilinx/PYNQ.git /tmp/pip-1yuva0i1-build" failed error code 128 in None_
Any suggestions as to how I install HDMI module ?

**Comment by giunatale** [comment]
Hi @shravan-red, I need to kindly ask you to redirect your question to our forum: https://discuss.pynq.io
That's the dedicated place to receive support from the community.
The issue tracker here is to report bugs in the codebase.

Closing this now, thanks in advance for your collaboration.
