### ISSUE TITLE
zedboard hdmi

### ISSUE THREAD

**Issue by m-pp** [Xilinx/PYNQ#924]
We have been trying to use the hdmi interface on zedboard with PYNQ. No success, anybody tried it and got it to work?

**Comment by giunatale** [comment]
Hi @m-pp, I need to ask you to redirect your question to our forum: https://discuss.pynq.io
That's the dedicated place to receive support from the community.
The issue tracker here is to report bugs in the codebase.

Closing this now, thanks in advance for your collaboration.
