### ISSUE TITLE
Trying to build pynq image for Mercury enclustra xu1

### ISSUE THREAD

**Issue by srinivasans74** [Xilinx/PYNQ#937]
device-tree-xilinx+gitAUTOINC+f38738e568-r0 do_compile: Function failed: do_compile

**Comment by giunatale** [comment]
@srinivasans74 Hi there, the message is not really informative, a full build log might be more helpful.

However, I also need to ask you to redirect your question to our forum: https://discuss.pynq.io
That's the dedicated place to receive support from the community. 
The issue tracker here is to report bugs in the codebase.

Closing this now, thanks in advance for your collaboration.
