### ISSUE TITLE
Control the GPIO pins using HLS C++ rather than Python

### ISSUE THREAD

**Issue by HonggangYu** [Xilinx/PYNQ#962]
Hi,

Recently I decided that I should start coding in HLS C++. I do know a fair amount of HLS C++ but I do not know how to control the GPIO pins on the PYNQ-Z1 board. Could you please explain to me (in the simplest way possible) how to control the GPIO pins using HLS C++ rather than python? Some simple example code (to light up a led?) would be greatly appreciated.

Thanks in advance to anyone who willingly can show me a way to control the GPIO pins using HLS C++.

**Comment by yunqu** [comment]
Hi, please follow the instruction in the pynq template - you should raise questions on discuss.pynq.io. I will close this.
