### ISSUE TITLE
Example notebooks not updated for new API

### ISSUE THREAD

**Issue by Recognition2** [Xilinx/PYNQ#963]
**For general questions, please use [the PYNQ discussion forum](https://discuss.
pynq.io/). We actively monitor the forum and try to answer every question 
there.**

Before submitting a pull request, you can also raise an issue that explains the 
problem the pull request is trying to resolve. Feel free to close the issue once
 the pull request has been merged.

If you still want to raise an issue here, please give us as much detail as 
possible to the issue you are seeing - we've listed some helpful fields below.

* PYNQ version (e.g. v2.5): v2.5
* Board name (e.g. Pynq-Z1): Pynq-Z2, but irrelevant
* Pull request type (bug fix / new feature): Example notebooks no longer work.
* Pull request number:
* Description:
Since the introduction of PYNQ v2.5, some library changes happened.
As a consequence of this, example files like those in `PYNQ/boards/Pynq-Z2/base/notebooks/` are no longer functional. They try to import `BaseOverlay` which no longer exists in pyn2.5.

**Comment by giunatale** [comment]
We cannot seem to be able to replicate using the provided SD card image. Can you provide more details on how to reproduce the issue?
