### ISSUE TITLE
How to support the ap_fixed type on the ip synthesised by vivado hls?

### ISSUE THREAD

**Issue by dongzwhitsz** [Xilinx/PYNQ#973]
How to support the ap_fixed type on the ip synthesised by vivado hls? I didn't fiind the way to communicate with the IP in the ap_fixed data type. Can this be realized by the python package?

**Comment by giunatale** [comment]
Hi @dongzwhitsz, I would kindly ask you to follow the issue template guidelines and redirect this question on the support forum https://discuss.pynq.io.
We restrict the issue tracker on this repo to issues and bug in the code base.
For support, we have the aforementioned dedicated forum where we usually reply fairly regularly.

I am closing this issue, thanks in advance for your patience and collaboration
