### ISSUE TITLE
we get the no internet and cant connect error on getting the version of the code from one computer to another

### ISSUE THREAD

**Issue by vishwas1234567** [Xilinx/PYNQ#994]
**For general questions, please use [the PYNQ discussion forum](https://discuss.
pynq.io/). We actively monitor the forum and try to answer every question 
there.**

Before submitting a pull request, you can also raise an issue that explains the 
problem the pull request is trying to resolve. Feel free to close the issue once
 the pull request has been merged.

If you still want to raise an issue here, please give us as much detail as 
possible to the issue you are seeing - we've listed some helpful fields below.

* PYNQ version (e.g. v2.5):
* Board name (e.g. Pynq-Z1):
* Pull request type (bug fix / new feature):
* Pull request number:
* Description:

**Comment by vishwas1234567** [comment]
![image](https://user-images.githubusercontent.com/48592314/73138647-38745000-408b-11ea-8356-a2b2f25fe565.png)

**Comment by vishwas1234567** [comment]
![image](https://user-images.githubusercontent.com/48592314/73139226-e08d1780-4091-11ea-9211-78b4cd06f7ec.png)



is this ok after the installation.

**Comment by vishwas1234567** [comment]
not that complete thing but thus 
![image](https://user-images.githubusercontent.com/48592314/73139241-ff8ba980-4091-11ea-828d-c7537e5fb36f.png)

**Comment by vishwas1234567** [comment]
this all happened when we did this process until then the boar was working fine.
![image](https://user-images.githubusercontent.com/48592314/73139400-c18f8500-4093-11ea-9bc8-96c19dc12d65.png)

**Comment by vishwas1234567** [comment]
https://docs.google.com/document/d/1JnOTYO-54EFyPGTecnlRaJsA72EqhBG_f69VFIz73nM/edit?usp=sharing

the thing we found working can be found here.

**Comment by giunatale** [comment]
Hi @vishwas1234567, please adhere to the issue template for a next time.
Secondly, as this seems more of a support question, I will close this now and ask you to redirect your query to https://discuss.pynq.io/

Another request, try to comment the issue, using only screenshots is not going to make things clear.

Many thanks!
